### ISSUE TITLE
Petit probleme

### ISSUE THREAD

**Issue by RyUkApples** [ig0ne/esx_holdup#1]
Je signale un bug, si je sors de la superette en plein braquage, celui ci est annulé hors, je gagnerais quand meme l'argent une le compteur terminé

**Comment by ig0ne** [comment]
j'ai fait un commit dit moi si ça fonctionne pour toi mais en tous cas plus de problème pour moi

**Comment by RyUkApples** [comment]
Je vais test

**Comment by RyUkApples** [comment]
Toujours present

**Comment by ig0ne** [comment]
je n'ai personnellement pas de problème du coup si tu n'as pas d'erreur je ne sais pas comment t'aider

**Comment by RyUkApples** [comment]
J'ai pas d'erreur, juste que je fais un braquage, je sors de la superette il est bien annuler mais je vais comme meme gagner la tune..

**Comment by TonTonSheitan** [comment]
Salut, moi quand je quitte le braquage je ne reçois pas l'argent donc sa fonctionne bien pour moi, apres quand je quitte le braquage j'ai des message d'erreur qui apparaisse , mais je pense que sa doit venir de ma version de extended

**Comment by ig0ne** [comment]
j'ai aussi les messages d'erreur mais le braquage est bien annulé et je ne touche pas d'argent. Donc je ne sais pas du tout d’où provient ton problème

**Comment by TonTonSheitan** [comment]
Petite questions ig0ne, les policier ne reçoivent pas la notification du braquage et impossible a changer le nombre de policier en service pour pouvoir braqué

**Comment by RyUkApples** [comment]
Au pire modifie le code et fais que sa set le reward du braquage sur zero si il est annulé ...

**Comment by ig0ne** [comment]
Je vais réessayer tous ça mais pour moi aucun problème pendant mes phases de test. Par contre je pourrais pas faire de changement ce soir

**Comment by RyUkApples** [comment]
Tu veux que jle fasse et jte le met en pull request apres ?

**Comment by RyUkApples** [comment]
En meme temps je fais un truc pour mettre un point sur le gps au flics..
Pour recuperer la pos des magasin c'est ça ?? 

local store.position = 'x','y'
local 'x','y' = x,y

sachant que pour mettre un point c'est ca

SetNewWaypoint(x,y)

**Comment by ig0ne** [comment]
@RyUkApples si tu as le temps de le faire ça me convient car je ne pourrais pas bosser dessus tout de suite et je ne pourrais pas le tester avec plusieurs personne avant 1/2 jours
