### ISSUE TITLE
Toujour braquage en cours ?

### ISSUE THREAD

**Issue by cedricalpatch** [ig0ne/esx_holdup#1]
Bonjour et merci pour ce beau travaille, mai il ne fonctionne pas chez moi !
Quant il y a un policier le braquage est toujours en cours...

Cordialement

**Comment by ig0ne** [comment]
Désolé de te répondre que maintenant mais sur mon serveur aucun soucis.
Pense bien à reboot ton serveur au moins toutes les 6h sinon le SQL et les scripts partent en couille :/
